POST http://localhost:3000/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiaGFtZWR6aWJpQGdtYWlsLmNvbSIsImlhdCI6MTc3NzgyMjMyMCwiZXhwIjoxNzc3ODI1OTIwLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.twr3IA5McJ1c_n53gTIAUkv_qD9P9_jah_hSu0-yrfQ

{
  "title": "Whats new with React 23",
  "postType": "post",
  "slug": "new-with-react23",
  "status": "draft",
  "content": "test content",
  "schema": "{\r\n \"@context\":\"https:\/\/schema.org\",\r\n \"@type\": \"Person\"\r\n}",
  "featuredImageUrl": "http://localhost.com/img/image1.png",
  "publishOn": "2024-03-16T07:46:32+0000",
  "metaOptions": {
    "metaValue": "{\"sidebarEnabled\":true , \"footerActive\":true}"
  },
  "tags": [
    1
  ]
}

